version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=typerace
      - DB_PASSWORD=typerace123
      - DB_NAME=typerace
      - REDIS_URL=redis:6379
      - JWT_SECRET=your-secret-key

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=typerace
      - POSTGRES_PASSWORD=typerace123
      - POSTGRES_DB=typerace
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: